name: WhereIs
version: 2.2.0
main: me.varchar42.whereis.WhereIsPlugin
author: VarChar42
commands:
  whereis:
    usage: /whereis <find | setup> <name |servername>
  otp:
    usage: /otp <name> <x> <y> <z>